[2022-09-14 14:09:30,242] {processor.py:153} INFO - Started process (PID=7586) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:09:30,242] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 14:09:30,243] {logging_mixin.py:115} INFO - [2022-09-14 14:09:30,242] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:09:30,256] {logging_mixin.py:115} INFO - [2022-09-14 14:09:30,256] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 14:09:30,256] {logging_mixin.py:115} INFO - [2022-09-14 14:09:30,256] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 14:09:30,256] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:09:30,266] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-14 14:11:38,251] {processor.py:153} INFO - Started process (PID=8030) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:11:38,252] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 14:11:38,253] {logging_mixin.py:115} INFO - [2022-09-14 14:11:38,253] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:11:38,267] {logging_mixin.py:115} INFO - [2022-09-14 14:11:38,266] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 14:11:38,267] {logging_mixin.py:115} INFO - [2022-09-14 14:11:38,267] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 14:11:38,267] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:11:38,277] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-14 14:12:40,372] {processor.py:153} INFO - Started process (PID=8346) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:12:40,374] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 14:12:40,374] {logging_mixin.py:115} INFO - [2022-09-14 14:12:40,374] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:12:40,389] {logging_mixin.py:115} INFO - [2022-09-14 14:12:40,388] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 14:12:40,389] {logging_mixin.py:115} INFO - [2022-09-14 14:12:40,389] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 14:12:40,389] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 14:12:40,400] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2022-09-14 20:21:58,365] {processor.py:153} INFO - Started process (PID=28347) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:21:58,368] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:21:58,369] {logging_mixin.py:115} INFO - [2022-09-14 20:21:58,368] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:21:58,387] {logging_mixin.py:115} INFO - [2022-09-14 20:21:58,387] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:21:58,387] {logging_mixin.py:115} INFO - [2022-09-14 20:21:58,387] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:21:58,388] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:21:58,398] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2022-09-14 20:24:04,165] {processor.py:153} INFO - Started process (PID=29489) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:24:04,167] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:24:04,168] {logging_mixin.py:115} INFO - [2022-09-14 20:24:04,168] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:24:04,186] {logging_mixin.py:115} INFO - [2022-09-14 20:24:04,186] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:24:04,186] {logging_mixin.py:115} INFO - [2022-09-14 20:24:04,186] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:24:04,187] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:24:04,197] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2022-09-14 20:24:39,396] {processor.py:153} INFO - Started process (PID=29616) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:24:39,398] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:24:39,398] {logging_mixin.py:115} INFO - [2022-09-14 20:24:39,398] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:24:39,416] {logging_mixin.py:115} INFO - [2022-09-14 20:24:39,416] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:24:39,417] {logging_mixin.py:115} INFO - [2022-09-14 20:24:39,416] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:24:39,417] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:24:39,427] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2022-09-14 20:25:27,738] {processor.py:153} INFO - Started process (PID=29912) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:25:27,739] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:25:27,740] {logging_mixin.py:115} INFO - [2022-09-14 20:25:27,740] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:25:27,754] {logging_mixin.py:115} INFO - [2022-09-14 20:25:27,754] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:25:27,754] {logging_mixin.py:115} INFO - [2022-09-14 20:25:27,754] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:25:27,754] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:25:27,765] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2022-09-14 20:26:03,205] {processor.py:153} INFO - Started process (PID=29954) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:26:03,206] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:26:03,207] {logging_mixin.py:115} INFO - [2022-09-14 20:26:03,207] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:26:03,222] {logging_mixin.py:115} INFO - [2022-09-14 20:26:03,221] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:26:03,222] {logging_mixin.py:115} INFO - [2022-09-14 20:26:03,222] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:26:03,222] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:26:03,233] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2022-09-14 20:30:50,860] {processor.py:153} INFO - Started process (PID=33480) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:30:50,863] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:30:50,863] {logging_mixin.py:115} INFO - [2022-09-14 20:30:50,863] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:30:50,877] {logging_mixin.py:115} INFO - [2022-09-14 20:30:50,877] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:30:50,877] {logging_mixin.py:115} INFO - [2022-09-14 20:30:50,877] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:30:50,878] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:30:50,889] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2022-09-14 20:31:26,018] {processor.py:153} INFO - Started process (PID=33771) to work on /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:31:26,019] {processor.py:641} INFO - Processing file /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-14 20:31:26,020] {logging_mixin.py:115} INFO - [2022-09-14 20:31:26,020] {dagbag.py:508} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:31:26,035] {logging_mixin.py:115} INFO - [2022-09-14 20:31:26,034] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-14 20:31:26,035] {logging_mixin.py:115} INFO - [2022-09-14 20:31:26,035] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-14 20:31:26,035] {processor.py:653} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-14 20:31:26,046] {processor.py:161} INFO - Processing /home/ubuntu/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
