[2022-09-05 12:16:14,657] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-05T11:41:09.189806+00:00 [queued]>
[2022-09-05 12:16:14,663] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-05T11:41:09.189806+00:00 [queued]>
[2022-09-05 12:16:14,663] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 12:16:14,663] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-05 12:16:14,663] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 12:16:14,678] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fit_model> on 2022-09-05 11:41:09.189806+00:00
[2022-09-05 12:16:14,683] {standard_task_runner.py:52} INFO - Started process 34360 to run task
[2022-09-05 12:16:14,687] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'fit_model', 'scheduled__2022-09-05T11:41:09.189806+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmplsu_9ls_', '--error-file', '/tmp/tmp__1hzcuk']
[2022-09-05 12:16:14,687] {standard_task_runner.py:80} INFO - Job 135: Subtask fit_model
[2022-09-05 12:16:14,734] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-05T11:41:09.189806+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-05 12:16:14,788] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=fit_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T11:41:09.189806+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T11:41:09.189806+00:00
[2022-09-05 12:16:14,790] {train_model.py:37} INFO - GOT INTO TRAIN FUNCTION
[2022-09-05 12:16:14,795] {train_model.py:41} INFO - Data path: /user/airflow/processed_files/partition_46.parquet
[2022-09-05 12:16:54,397] {logging_mixin.py:115} WARNING - 2022/09/05 12:16:54 WARNING mlflow.pyspark.ml: Model inputs contain unsupported Spark data types: [StructField(featuresFinal,VectorUDT,true)]. Model signature is not logged.
[2022-09-05 12:17:10,094] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-05 12:17:27,133] {train_model.py:70} INFO - Accuracy SCORE: 0.5
[2022-09-05 12:17:27,163] {python.py:173} INFO - Done. Returned value was: None
[2022-09-05 12:17:27,172] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=fit_model, execution_date=20220905T114109, start_date=20220905T121614, end_date=20220905T121727
[2022-09-05 12:17:27,227] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05 12:17:27,237] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
