[2022-09-15 15:59:19,696] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-15T15:43:27.007011+00:00 [queued]>
[2022-09-15 15:59:19,701] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-15T15:43:27.007011+00:00 [queued]>
[2022-09-15 15:59:19,701] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 15:59:19,701] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-15 15:59:19,701] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 15:59:19,725] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fit_model> on 2022-09-15 15:43:27.007011+00:00
[2022-09-15 15:59:19,732] {standard_task_runner.py:52} INFO - Started process 54890 to run task
[2022-09-15 15:59:19,735] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'fit_model', 'scheduled__2022-09-15T15:43:27.007011+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmpqv9fd5tu', '--error-file', '/tmp/tmppjq8_x6r']
[2022-09-15 15:59:19,736] {standard_task_runner.py:80} INFO - Job 278: Subtask fit_model
[2022-09-15 15:59:19,781] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-15T15:43:27.007011+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-15 15:59:19,834] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=fit_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-15T15:43:27.007011+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-15T15:43:27.007011+00:00
[2022-09-15 15:59:19,835] {train_model.py:37} INFO - GOT INTO TRAIN FUNCTION
[2022-09-15 15:59:19,841] {train_model.py:42} INFO - Data path: /user/airflow/processed_files/slice_of_65_75.parquet
[2022-09-15 16:01:14,821] {logging_mixin.py:115} WARNING - 2022/09/15 16:01:14 WARNING mlflow.pyspark.ml: Model inputs contain unsupported Spark data types: [StructField(featuresFinal,VectorUDT,true)]. Model signature is not logged.
[2022-09-15 16:01:33,365] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-15 16:01:48,541] {train_model.py:71} INFO - Accuracy SCORE: 0.6149351575593779
[2022-09-15 16:01:48,569] {python.py:173} INFO - Done. Returned value was: None
[2022-09-15 16:01:48,579] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=fit_model, execution_date=20220915T154327, start_date=20220915T155919, end_date=20220915T160148
[2022-09-15 16:01:48,619] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-15 16:01:48,640] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
