[2022-06-26 15:13:32,820] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: fraud_generation.generate_transaction scheduled__2022-06-26T15:03:26.520548+00:00 [queued]>
[2022-06-26 15:13:32,881] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: fraud_generation.generate_transaction scheduled__2022-06-26T15:03:26.520548+00:00 [queued]>
[2022-06-26 15:13:32,881] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-26 15:13:32,881] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-26 15:13:32,881] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-26 15:13:33,006] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): generate_transaction> on 2022-06-26 15:03:26.520548+00:00
[2022-06-26 15:13:33,038] {standard_task_runner.py:52} INFO - Started process 158 to run task
[2022-06-26 15:13:33,055] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fraud_generation', 'generate_transaction', 'scheduled__2022-06-26T15:03:26.520548+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/fraud_generation_dag.py', '--cfg-path', '/tmp/tmp7j3wy8d7', '--error-file', '/tmp/tmplrm6w0x0']
[2022-06-26 15:13:33,056] {standard_task_runner.py:80} INFO - Job 197: Subtask generate_transaction
[2022-06-26 15:13:33,490] {task_command.py:370} INFO - Running <TaskInstance: fraud_generation.generate_transaction scheduled__2022-06-26T15:03:26.520548+00:00 [running]> on host e40375faaea0
[2022-06-26 15:13:34,009] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fraud_generation
AIRFLOW_CTX_TASK_ID=generate_transaction
AIRFLOW_CTX_EXECUTION_DATE=2022-06-26T15:03:26.520548+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-26T15:03:26.520548+00:00
[2022-06-26 15:13:34,011] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-26 15:13:34,012] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/script_generation.py 15422']
[2022-06-26 15:13:34,113] {subprocess.py:85} INFO - Output:
[2022-06-26 15:13:37,588] {subprocess.py:92} INFO - /tmp/***tmpg4fdcu_g
[2022-06-26 15:13:37,691] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-26 15:13:37,744] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=fraud_generation, task_id=generate_transaction, execution_date=20220626T150326, start_date=20220626T151332, end_date=20220626T151337
[2022-06-26 15:13:37,782] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-26 15:13:37,843] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
